# Generated by Django 2.0.2 on 2018-05-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180522_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=256)),
                ('kind', models.ForeignKey(on_delete='cascade', to='main.Foods')),
            ],
        ),
        migrations.DeleteModel(
            name='Burger',
        ),
        migrations.DeleteModel(
            name='Desert',
        ),
        migrations.DeleteModel(
            name='Pizza',
        ),
        migrations.DeleteModel(
            name='Pyrog',
        ),
        migrations.DeleteModel(
            name='Salad',
        ),
        migrations.DeleteModel(
            name='Shashlik',
        ),
        migrations.DeleteModel(
            name='Sushi',
        ),
    ]
