# Generated by Django 2.0.2 on 2018-05-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180522_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='price',
            field=models.DecimalField(decimal_places=2, default=123, max_digits=8),
            preserve_default=False,
        ),
    ]
