# Generated by Django 2.0.2 on 2018-05-22 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_food_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='restaurants',
            field=models.ManyToManyField(to='main.Restaurant'),
        ),
    ]
